openapi: 3.0.0
info:
  title: Sample data access API
  description: Data access API for upload and download of dataset distributions
  version: 0.0.1
  contact:
    name: Dataplatform team
    email: dataplattform@oslo.kommune.no

paths:
  /datasets:
    get:
      description: Returns a list of datasets
      operationId: listDatasets
      responses:
        '200':
          description: A JSON array of datasets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
