openapi: 3.0.0
info:
  version: 0.0.1
  title: Metadata API
  description: Metadata API for registering and accessing metadata about datasets and distributions
  contact:
    name: Dataplatform team
    email: dataplattform@oslo.kommune.no

paths:
  /datasets:
    get:
      summary: Returns a list of datasets
      description: Returns a list of datasets
      operationId: list_datasets
      responses:
        '200':
          description: A JSON array of datasets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: ${lambda_uri}
        httpMethod: POST
        responses:
          default:
            statusCode: '200'
