frameworkVersion: ">=1.50.0 <2.0.0"
service: metadata-api

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ok-origo-dataplatform-config-${self:provider.stage}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  tracing:
    lambda: true
    apiGateway: true
  iamManagedPolicies:
    - Fn::Join:
      - ':'
      - - 'arn:aws:iam:'
        - Ref: AWS::AccountId
        - 'policy/metadata-api-policy'
    - Fn::Join:
        - ':'
        - - 'arn:aws:iam::aws'
          - 'policy/AWSXRayDaemonWriteAccess'
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}

plugins:
  - serverless-aws-documentation
  - serverless-python-requirements
  - serverless-scriptable-plugin
  - serverless-plugin-git-variables
package:
  exclude:
    - './**'
  include:
    - './metadata/*.py'
    - './metadata/dataset/*.py'
    - './metadata/version/*.py'
    - './metadata/edition/*.py'
    - './metadata/distribution/*.py'

resources:
  Description: >
    ${self:service} ${git:branch}:${git:sha1}

    ${git:message}


custom:
  scriptHooks:
    after:deploy:finalize: make update-ssm-${self:provider.stage}
  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: false
  documentation:
    version: '0.5.0'
    title: 'Metadata-api'
    description: 'Metadata-api for dataplattform'
    models:
      - ${file(serverless/models/ErrorResponse.yaml)}
      - ${file(serverless/models/Response.yaml)}
      - ${file(serverless/models/Request.yaml)}
  exportGitVariables: false

functions:
  create_dataset: ${file(serverless/functions/create_dataset.yaml)}
  get_datasets: ${file(serverless/functions/get_datasets.yaml)}
  get_dataset:  ${file(serverless/functions/get_dataset.yaml)}
  update_dataset: ${file(serverless/functions/update_dataset.yaml)}
  create_version: ${file(serverless/functions/create_version.yaml)}
  update_version: ${file(serverless/functions/update_version.yaml)}
  get_versions: ${file(serverless/functions/get_versions.yaml)}
  get_version: ${file(serverless/functions/get_version.yaml)}
  create_edition: ${file(serverless/functions/create_edition.yaml)}
  update_edition: ${file(serverless/functions/update_edition.yaml)}
  get_editions: ${file(serverless/functions/get_editions.yaml)}
  get_edition: ${file(serverless/functions/get_edition.yaml)}
  create_distribution: ${file(serverless/functions/create_distribution.yaml)}
  put_distribution: ${file(serverless/functions/put_distribution.yaml)}
  get_distributions: ${file(serverless/functions/get_distributions.yaml)}
  get_distribution: ${file(serverless/functions/get_distribution.yaml)}
